unlink('tmp', recursive=TRUE)
dir.create('tmp')
file.copy('./test/X_test.txt', 'tmp')
file.copy('./test/y_test.txt', 'tmp')
file.copy('./test/subject_test.txt', 'tmp')
file.append('./tmp/X_test.txt', './train/X_train.txt')
file.append('./tmp/y_test.txt', './train/y_train.txt')
file.append('./tmp/subject_test.txt', './train/subject_train.txt')
df1 <- read.table('./tmp/X_test.txt')
df2 <- read.table('./tmp/y_test.txt')
df3 <- read.table('./tmp/subject_test.txt')
df2$V1 <- factor(df2$V1, levels=c(1:6), 
          labels=c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIRS","SITTING","STANDING","LAYING"))
means1 <- data.frame(rowMeans(df1))
sd1 <- data.frame(apply(as.matrix(df1), 1, sd))
frame1 <- data.frame(activity=df2$V1, subject=df3$V1, mean=means1[,1], std=sd1[,1])
frame2 <- ddply(frame1,subject~activity,summarize, mean=mean(mean), std=mean(std))
write.table(frame2, file="tidy_data.txt", row.names=FALSE)